-- B Reddy Sales - complete Supabase schema
-- Run this whole file once in Supabase SQL Editor.
-- The client uses the publishable key, so these demo policies allow the app to work.
-- Before real production use, replace the anon write policies with authenticated RLS.

create table if not exists customers (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  mobile_no text,
  address text,
  opening_due numeric(14,2) not null default 0,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists item_master (
  id bigint generated by default as identity primary key,
  master_name text,
  item_name text not null,
  sale_rate numeric(14,2) not null default 0,
  purchase_rate numeric(14,2) not null default 0,
  opening_stock numeric(14,2) not null default 0,
  minimum_stock numeric(14,2) not null default 0,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists receivers (
  id bigint generated by default as identity primary key,
  receiver_name text not null,
  receiver_type text not null default 'Cash',
  opening_balance numeric(14,2) not null default 0,
  current_balance numeric(14,2) not null default 0,
  status boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists suppliers (
  id bigint generated by default as identity primary key,
  supplier_name text not null,
  mobile_no text,
  address text,
  opening_due numeric(14,2) not null default 0,
  status boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists sales (
  id bigint generated by default as identity primary key,
  invoice_no text not null unique,
  invoice_date date not null default current_date,
  customer_id bigint not null references customers(id),
  total_amount numeric(14,2) not null default 0,
  paid_amount numeric(14,2) not null default 0,
  due_amount numeric(14,2) not null default 0,
  payment_status text not null default 'DUE' check (payment_status in ('PAID','PARTIAL','DUE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references sales(id) on delete cascade,
  item_id bigint not null references item_master(id),
  rate numeric(14,2) not null default 0,
  qty numeric(14,2) not null default 0,
  amount numeric(14,2) not null default 0
);

create table if not exists collections (
  id bigint generated by default as identity primary key,
  collection_no text not null unique,
  collection_date date not null default current_date,
  customer_id bigint not null references customers(id),
  receiver_id bigint not null references receivers(id),
  total_amount numeric(14,2) not null default 0,
  remarks text,
  created_at timestamptz not null default now()
);

create table if not exists collection_allocations (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references collections(id) on delete cascade,
  sale_id bigint not null references sales(id),
  amount numeric(14,2) not null default 0
);

create table if not exists purchases (
  id bigint generated by default as identity primary key,
  purchase_no text not null unique,
  purchase_date date not null default current_date,
  supplier_id bigint not null references suppliers(id),
  total_amount numeric(14,2) not null default 0,
  paid_amount numeric(14,2) not null default 0,
  due_amount numeric(14,2) not null default 0,
  payment_status text not null default 'DUE' check (payment_status in ('PAID','PARTIAL','DUE')),
  receiver_id bigint references receivers(id),
  created_at timestamptz not null default now()
);

create table if not exists purchase_items (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references purchases(id) on delete cascade,
  item_id bigint not null references item_master(id),
  rate numeric(14,2) not null default 0,
  qty numeric(14,2) not null default 0,
  amount numeric(14,2) not null default 0
);

create table if not exists stock_transactions (
  id bigint generated by default as identity primary key,
  transaction_date date not null default current_date,
  item_id bigint not null references item_master(id),
  transaction_type text not null,
  reference_id bigint,
  qty_in numeric(14,2) not null default 0,
  qty_out numeric(14,2) not null default 0,
  rate numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create sequence if not exists invoice_number_seq start 1;
create sequence if not exists purchase_number_seq start 1;

create or replace function next_invoice_number()
returns text
language plpgsql
as $$
begin
  return 'INV-' || lpad(nextval('invoice_number_seq')::text, 4, '0');
end;
$$;

create or replace function next_purchase_number()
returns text
language plpgsql
as $$
begin
  return 'PUR-' || lpad(nextval('purchase_number_seq')::text, 4, '0');
end;
$$;

-- If tables were created earlier, this safely adds the missing tables/functions.
alter table customers enable row level security;
alter table item_master enable row level security;
alter table receivers enable row level security;
alter table suppliers enable row level security;
alter table sales enable row level security;
alter table sale_items enable row level security;
alter table collections enable row level security;
alter table collection_allocations enable row level security;
alter table purchases enable row level security;
alter table purchase_items enable row level security;
alter table stock_transactions enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array['customers','item_master','receivers','suppliers','sales','sale_items','collections','collection_allocations','purchases','purchase_items','stock_transactions']
  loop
    execute format('drop policy if exists "public_select_%s" on %I', t, t);
    execute format('drop policy if exists "public_insert_%s" on %I', t, t);
    execute format('drop policy if exists "public_update_%s" on %I', t, t);
    execute format('drop policy if exists "public_delete_%s" on %I', t, t);

    execute format('create policy "public_select_%s" on %I for select to anon using (true)', t, t);
    execute format('create policy "public_insert_%s" on %I for insert to anon with check (true)', t, t);
    execute format('create policy "public_update_%s" on %I for update to anon using (true) with check (true)', t, t);
    execute format('create policy "public_delete_%s" on %I for delete to anon using (true)', t, t);
  end loop;
end $$;
