-- B Reddy Sales V4 upgrade
-- Run this once in Supabase SQL Editor after deploying the V4 project.

create table if not exists expense_types (
  id bigint generated by default as identity primary key,
  type_name text not null unique,
  description text,
  status boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  expense_date date not null default current_date,
  expense_type_id bigint not null references expense_types(id),
  amount numeric(14,2) not null default 0,
  paid_by text not null default 'Business' check (paid_by in ('Business','Supplier')),
  receiver_id bigint references receivers(id),
  reference_type text,
  reference_id bigint,
  remarks text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table purchases add column if not exists transportation_charge numeric(14,2) not null default 0;
alter table purchases add column if not exists loading_charge numeric(14,2) not null default 0;
alter table purchases add column if not exists unloading_charge numeric(14,2) not null default 0;
alter table purchases add column if not exists charges_paid_by text not null default 'Business';
alter table purchases add column if not exists charges_receiver_id bigint references receivers(id);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id bigint,
  action text not null,
  details jsonb,
  created_at timestamptz not null default now()
);

alter table expense_types enable row level security;
alter table expenses enable row level security;
alter table audit_logs enable row level security;

do $$
declare t text;
begin
  foreach t in array array['expense_types','expenses','audit_logs']
  loop
    execute format('drop policy if exists "public_select_%s" on %I', t, t);
    execute format('drop policy if exists "public_insert_%s" on %I', t, t);
    execute format('drop policy if exists "public_update_%s" on %I', t, t);
    execute format('drop policy if exists "public_delete_%s" on %I', t, t);
    execute format('create policy "public_select_%s" on %I for select to anon using (true)', t, t);
    execute format('create policy "public_insert_%s" on %I for insert to anon with check (true)', t, t);
    execute format('create policy "public_update_%s" on %I for update to anon using (true) with check (true)', t, t);
    execute format('create policy "public_delete_%s" on %I for delete to anon using (true)', t, t);
  end loop;
end $$;

insert into expense_types(type_name,description) values
 ('Transportation','Transport/freight charges related to purchase'),
 ('Loading & Unloading','Loading and unloading charges'),
 ('Other','Other business expenses')
on conflict (type_name) do nothing;

create or replace function b_reddy_audit_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare rid bigint; payload jsonb;
begin
  if TG_OP='DELETE' then rid := (to_jsonb(OLD)->>'id')::bigint; payload := to_jsonb(OLD);
  elsif TG_OP='UPDATE' then rid := (to_jsonb(NEW)->>'id')::bigint; payload := jsonb_build_object('old',to_jsonb(OLD),'new',to_jsonb(NEW));
  else rid := (to_jsonb(NEW)->>'id')::bigint; payload := to_jsonb(NEW);
  end if;
  insert into audit_logs(table_name,record_id,action,details) values(TG_TABLE_NAME,rid,TG_OP,payload);
  return coalesce(NEW,OLD);
end;
$$;

drop trigger if exists audit_customers on customers;
create trigger audit_customers after insert or update or delete on customers for each row execute function b_reddy_audit_trigger();
drop trigger if exists audit_sales on sales;
create trigger audit_sales after insert or update or delete on sales for each row execute function b_reddy_audit_trigger();
drop trigger if exists audit_collections on collections;
create trigger audit_collections after insert or update or delete on collections for each row execute function b_reddy_audit_trigger();
drop trigger if exists audit_purchases on purchases;
create trigger audit_purchases after insert or update or delete on purchases for each row execute function b_reddy_audit_trigger();
drop trigger if exists audit_expenses on expenses;
create trigger audit_expenses after insert or update or delete on expenses for each row execute function b_reddy_audit_trigger();
drop trigger if exists audit_receivers on receivers;
create trigger audit_receivers after insert or update or delete on receivers for each row execute function b_reddy_audit_trigger();
drop trigger if exists audit_items on item_master;
create trigger audit_items after insert or update or delete on item_master for each row execute function b_reddy_audit_trigger();

do $$
begin
  begin alter publication supabase_realtime add table expense_types; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table expenses; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table audit_logs; exception when duplicate_object then null; end;
end $$;


-- ============================================================
-- V5 Authentication: Admin + Receiver
-- Supabase Auth stores passwords. user_profiles stores only role/display data.
-- ============================================================

create table if not exists user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text,
  role text not null default 'receiver' check (role in ('admin','receiver')),
  receiver_id bigint references receivers(id),
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table user_profiles enable row level security;

create or replace function current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from user_profiles where id = auth.uid() and status = true limit 1;
$$;

create or replace function is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from user_profiles where id=auth.uid() and role='admin' and status=true);
$$;

create or replace function is_receiver()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from user_profiles where id=auth.uid() and role='receiver' and status=true);
$$;

grant execute on function current_user_role() to authenticated;
grant execute on function is_admin() to authenticated;
grant execute on function is_receiver() to authenticated;

-- Remove old public/anonymous access. The application now requires login.
do $$
declare t text;
begin
  foreach t in array array['customers','item_master','receivers','suppliers','sales','sale_items','collections','collection_allocations','purchases','purchase_items','stock_transactions','expense_types','expenses','audit_logs','user_profiles']
  loop
    execute format('drop policy if exists "public_select_%s" on %I', t, t);
    execute format('drop policy if exists "public_insert_%s" on %I', t, t);
    execute format('drop policy if exists "public_update_%s" on %I', t, t);
    execute format('drop policy if exists "public_delete_%s" on %I', t, t);
  end loop;
end $$;

-- Read access
create policy "auth_select_data" on customers for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_items" on item_master for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_receivers" on receivers for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_suppliers" on suppliers for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_sales" on sales for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_sale_items" on sale_items for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_collections" on collections for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_collection_allocations" on collection_allocations for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_purchases" on purchases for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_purchase_items" on purchase_items for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_stock_transactions" on stock_transactions for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_expense_types" on expense_types for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_expenses" on expenses for select to authenticated using (is_admin() or is_receiver());
create policy "auth_select_user_profiles" on user_profiles for select to authenticated using (id=auth.uid() or is_admin());
create policy "auth_select_audit_logs" on audit_logs for select to authenticated using (is_admin());

-- Admin has full CRUD
do $$
declare t text;
begin
  foreach t in array array['customers','item_master','receivers','suppliers','sales','sale_items','collections','collection_allocations','purchases','purchase_items','stock_transactions','expense_types','expenses','audit_logs','user_profiles']
  loop
    execute format('create policy "admin_insert_%s" on %I for insert to authenticated with check (is_admin())', t, t);
    execute format('create policy "admin_update_%s" on %I for update to authenticated using (is_admin()) with check (is_admin())', t, t);
    execute format('create policy "admin_delete_%s" on %I for delete to authenticated using (is_admin())', t, t);
  end loop;
end $$;

-- Receiver permissions: can record/edit collections and payment-related sales/receiver balances,
-- but cannot alter master data, purchases, expenses, or audit history.
create policy "receiver_insert_collections" on collections for insert to authenticated with check (is_receiver() and receiver_id=(select receiver_id from user_profiles where id=auth.uid()));
create policy "receiver_update_collections" on collections for update to authenticated using (is_receiver() and receiver_id=(select receiver_id from user_profiles where id=auth.uid())) with check (is_receiver() and receiver_id=(select receiver_id from user_profiles where id=auth.uid()));
create policy "receiver_insert_allocations" on collection_allocations for insert to authenticated with check (is_receiver());
create policy "receiver_update_allocations" on collection_allocations for update to authenticated using (is_receiver()) with check (is_receiver());
create policy "receiver_update_sales" on sales for update to authenticated using (is_receiver()) with check (is_receiver());
create policy "receiver_update_receivers" on receivers for update to authenticated using (is_receiver() and id=(select receiver_id from user_profiles where id=auth.uid())) with check (is_receiver() and id=(select receiver_id from user_profiles where id=auth.uid()));

-- No receiver delete policies. RLS therefore blocks receiver deletes.

-- Audit trail now stores the authenticated user's ID, name and role.
alter table audit_logs add column if not exists user_id uuid references auth.users(id);
alter table audit_logs add column if not exists user_name text;
alter table audit_logs add column if not exists user_role text;

create or replace function b_reddy_audit_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  rid bigint;
  payload jsonb;
  uname text;
  urole text;
begin
  if TG_OP='DELETE' then
    rid := (to_jsonb(OLD)->>'id')::bigint;
    payload := to_jsonb(OLD);
  elsif TG_OP='UPDATE' then
    rid := (to_jsonb(NEW)->>'id')::bigint;
    payload := jsonb_build_object('old',to_jsonb(OLD),'new',to_jsonb(NEW));
  else
    rid := (to_jsonb(NEW)->>'id')::bigint;
    payload := to_jsonb(NEW);
  end if;

  select full_name, role into uname, urole from user_profiles where id=auth.uid();
  insert into audit_logs(table_name,record_id,action,details,user_id,user_name,user_role)
  values(TG_TABLE_NAME,rid,TG_OP,payload,auth.uid(),coalesce(uname,'System'),coalesce(urole,'system'));
  return coalesce(NEW,OLD);
end;
$$;

-- Existing triggers continue to use the updated function.
