-- B REDDY SALES V7
-- Custom application login. Supabase Auth is no longer used by the app.
-- Passwords are stored only as bcrypt hashes using pgcrypto.
-- The browser talks to Next.js API routes; the service-role key stays server-side.

create extension if not exists pgcrypto;

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('admin','receiver')),
  receiver_id bigint references public.receivers(id),
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_sessions_token on public.app_sessions(token_hash);
create index if not exists idx_app_sessions_expiry on public.app_sessions(expires_at);
create index if not exists idx_app_users_email on public.app_users(lower(email));

alter table public.app_users enable row level security;
alter table public.app_sessions enable row level security;

-- No public/anon/authenticated policies are created. Only the server's service-role client can access these tables.

create or replace function public.verify_app_password(p_password text, p_password_hash text)
returns boolean
language sql
security definer
set search_path = public, extensions
as $$
  select crypt(p_password, p_password_hash) = p_password_hash;
$$;

revoke all on function public.verify_app_password(text,text) from public, anon, authenticated;
grant execute on function public.verify_app_password(text,text) to service_role;

create or replace function public.create_or_update_app_user(
  p_email text,
  p_password text,
  p_full_name text,
  p_role text,
  p_receiver_id bigint default null,
  p_status boolean default true
)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare v_id bigint;
begin
  if p_role not in ('admin','receiver') then raise exception 'Role must be admin or receiver'; end if;
  if p_role = 'receiver' and p_receiver_id is null then raise exception 'Receiver login requires receiver_id'; end if;
  insert into public.app_users(full_name,email,password_hash,role,receiver_id,status)
  values(p_full_name,lower(trim(p_email)),crypt(p_password,gen_salt('bf',10)),p_role,p_receiver_id,p_status)
  on conflict(email) do update set
    full_name=excluded.full_name,
    password_hash=excluded.password_hash,
    role=excluded.role,
    receiver_id=excluded.receiver_id,
    status=excluded.status,
    updated_at=now()
  returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.create_or_update_app_user(text,text,text,text,bigint,boolean) from public, anon, authenticated;
grant execute on function public.create_or_update_app_user(text,text,text,text,bigint,boolean) to service_role;

-- Remove expired sessions periodically by calling this from an admin/server job if desired.
create or replace function public.cleanup_expired_app_sessions()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare v_count integer;
begin
  delete from public.app_sessions where expires_at <= now();
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
revoke all on function public.cleanup_expired_app_sessions() from public, anon, authenticated;
grant execute on function public.cleanup_expired_app_sessions() to service_role;

-- The custom login does not need Supabase Auth user_profiles.
-- Keep existing user_profiles during transition; the V7 app does not read it.

-- Example: create your users. Replace the passwords with your own choices before running.
-- These commands hash the passwords; plaintext passwords are not stored.
-- select public.create_or_update_app_user('singarisurendra@gmail.com','CHANGE-ME','Surendra','admin',null,true);
-- select public.create_or_update_app_user('receiver1@breddysales.com','CHANGE-ME','B Reddy','receiver',2,true);

-- The V7 server API writes named audit rows. Disable the older auth.uid()-based triggers
-- so each business mutation does not create an extra "System" audit entry.
drop trigger if exists audit_customers on public.customers;
drop trigger if exists audit_sales on public.sales;
drop trigger if exists audit_collections on public.collections;
drop trigger if exists audit_purchases on public.purchases;
drop trigger if exists audit_expenses on public.expenses;
drop trigger if exists audit_receivers on public.receivers;
drop trigger if exists audit_items on public.item_master;

-- Explicitly revoke direct table privileges from browser-facing roles.
-- The server uses the service_role key and is the only data access path for V7.
revoke all on public.app_users from anon, authenticated;
revoke all on public.app_sessions from anon, authenticated;
revoke all on public.customers from anon, authenticated;
revoke all on public.item_master from anon, authenticated;
revoke all on public.receivers from anon, authenticated;
revoke all on public.suppliers from anon, authenticated;
revoke all on public.sales from anon, authenticated;
revoke all on public.sale_items from anon, authenticated;
revoke all on public.collections from anon, authenticated;
revoke all on public.collection_allocations from anon, authenticated;
revoke all on public.purchases from anon, authenticated;
revoke all on public.purchase_items from anon, authenticated;
revoke all on public.stock_transactions from anon, authenticated;
revoke all on public.expense_types from anon, authenticated;
revoke all on public.expenses from anon, authenticated;
revoke all on public.audit_logs from anon, authenticated;
revoke all on public.user_profiles from anon, authenticated;
